### ISSUE TITLE
Advice about input file of HapCHAT?

### ISSUE THREAD

**Issue by orangeSi** [AlgoLab/HapCHAT#1]
hi~
   I am new for this diploid genome phase assembly software.  Sorry for the stupid question~
   HapCHAT need input  genome.fasta + input.bam  + input.vcf,  so the genome.fasta is the pacbio raw diploid assemlby result(example canu assembly if I have 50x pacbio data),  and the the vcf is map the pacbio read to raw diploid assembly result to call snpindel? 
   The output is also phased vcf, so how do I get a phased haploid genome fasta ?

Thanks~
Si

**Comment by murraypatterson** [comment]
Hi,

Thanks for your interest in HapCHAT !

HapCHAT needs as input at least the `input.vcf` and `input.bam` files, which contain the variants (to be phased) and the reads, respectively.  VCF (variant call format) and BAM (binary sequence alignment map) formats are community standards for representing variants and readsets, respectively --- hence they are well-documented.  An optional `genome.fasta` can be provided if the user wants to activate the realignment step --- realignment of the reads against the reference genome: which is recommended for noisy reads like PacBio, for example.  Hence the `genome.fasta` is this reference genome, _e.g._, the human reference hg37, if we are haplotyping human DNA.

The output is a phased VCF, in the sense that it simply adds phasing information to the input `input.vcf` file.  As for obtaining fasta from this, I am not too familiar, but I think `bcftools` http://samtools.github.io/bcftools/bcftools.html has features for doing this --- maybe, given a reference genome `genome.fasta` and the phased VCF, for example, it can produce this fasta file that you need.

We hope we have answered your questions, but if not, or you have more, please do not hesitate to send us another message.

Best Wishes,
Murray

**Comment by orangeSi** [comment]
Thanks much for the detail kind introduction!
do you mean HapCHAT is mainly  for phase hete snpindel for resequencing  project instead of genome denovo assembly project ?

**Comment by murraypatterson** [comment]
No problem !  HapCHAT is simply a dynamic programming procedure for phasing single nucleotide variants (SNVs) --- as specified in a VCF file --- given _aligned_ reads containing these variants --- as specified in a BAM file --- and so it is suitable in any setting where this information is available

So, indeed, it does not perform the alignment.  A reference genome (to which the reads were supposedly aligned) can help with noisy long reads (PacBio, etc.), allowing for improved accuracy and recall when this info is available, but it is not a requirement

**Comment by murraypatterson** [comment]
I am closing this issue now, feel free to reopen it for any reason, however !
