### ISSUE TITLE
Input file issue

### ISSUE THREAD

**Issue by sinamajidian** [AlgoLab/HapCHAT#4]
Dear HapCHAT team
I intend to compare my algorithm to HapCHAT for a fragment matrix. This kind of data was used in RefHap, AltHap, and [ProbHap](https://github.com/kuleshov/ProbHap). I found out that HapCHAT needs a Bam and/or VCF file.
I have a question. Does HapCHAT support such file as input? 
It will be appreciated if you tell me a clue for doing so.
Best regards.

**Comment by murraypatterson** [comment]
Dear smajidian,

There could be some way to convert this fragment matrix into the internal representation that HapCHAT takes right before the phasing process ... what is the format of this fragment matrix ?

A better way might be to find (if you can) the BAM/VCF pair from which this fragment matrix came -- since BAM and VCF are community standard formats -- the BAM containing the reads (the rows), while the VCF contains where the variants (the columns) are in these reads.  Since HapCHAT adheres to the extensive specifications, e.g., VCF v4.1, of these standard formats, it would remove any guesswork regarding file formats

Of course, if you cannot find these, please let us know, and we will see what we can to do to help

Best,
Murray

**Comment by sinamajidian** [comment]
Dear Dr. Patterson
Thanks for your kind and fast response. 
The data has been generated before by [Geraci](http://bioalgo.iit.cnr.it/rehap/):

> Geraci, Filippo. "A comparison of several algorithms for the single individual SNP haplotyping reconstruction problem." Bioinformatics 26.18 (2010): 2217-2225.

A part of matrix is as following:

> acgtga------------------------
atgtg-----------------ctgtga--
attt-atcagcggtc-----------aag-
ttgt--------------------------
att---ggcac-------------------
---tga------------------------

Each row is a read containing just SNP loci. The "-"s in a row are those SNP loci which are not included in that read.  The column number of matrix equals to haplotype length. 

I think that a Bam file contains not only SNP loci but also the non-SNP loci. So, Bam file contains some more information than a fragment matrix which may not be used in haplotyping. Does HapChat use non-SNP part of a read?

I used this data for comparing my algorithm to some others. Now, a reviewer of journal ask me to compare with mine with HapCHAT.
Thank you in advance,
Sina.

**Comment by murraypatterson** [comment]
Dear Sina,

Yes, the BAM format specifies reads, containing all the loci, SNPs and non-SNPs, while the VCF file contains those positions where are SNPs (and some other information as well) -- from this pair one can obtain the SNP fragment matrix

However in this paper (Geraci, 2010) it seems that they generate their SNP fragment matrices directly -- I suppose you obtained these directly from Geraci?, as he states "The data we used to compare the algorithms are available on demand" -- if so, maybe he has the BAM and VCF from which his data was generated?

Cheers,
Murray

**Comment by sinamajidian** [comment]
Thanks dear Murray.
Yes, I directly received the data from Dr. Geraci. It seems that he just considered the SNPs.

> ..., the generation of the SNP matrix is as follows: given a pair of haplotypes of length l, each haplotype is replicated c times (the parameter c is called coverage), then each copy is broken into non-overlapping fragments ... we arrange the fragments in a matrix and insert errors according to a uniform distribution (Gereci, 2010).

You said that "There could be some way to convert this fragment matrix into the internal representation that HapCHAT takes right before the phasing process", but I think that this is not trivial and may need too much time for coding.
